mem: 100GB
threads: 8
output_dir: "results"
log_dir: "logs"
benchmarks: "benchmarks"
reference:
  - name: CHM13
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/T2T-CHM13v2.fasta
    bed:
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr1.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr2.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr3.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr4.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr5.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr6.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr7.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr8.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr9.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr10.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr11.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr12.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr13.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr14.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr15.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr16.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr17.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr18.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr19.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr20.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr21.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chr22.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chrX.bed
      - /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/windows/CHM13_chrY.bed
regex_sm_hap: "'(mat|pat|haplotype1|haplotype2|hap1|hap2|h1|h2)'"
regex_sm_chrom: "'_(hsa(.*?)|chr(.*?)|cen(.*?))[:_]'"
regex_ref_chrom: "(?:chr|hsa|cen)([0-9XY]{1,2})"
length_range: [8000, 12000]
# https://www.nature.com/articles/s41586-025-08816-3
samples:
  - name: HG00171
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/SG_working/fasta/HG00171.cen.fasta
    mm2_opts: -x asm20 -K 8G --eqx -Y -t 8 -r 500000,500000
    divergence_time: 0
  - name: mGorGor1
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/asm_primates/mGorGor1.matpat.v2.fa
    bed: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/regions_primates/mGorGor1.matpat.v2.centromeric_regions.bed
    mm2_opts: -x asm20 -K 8G --eqx -Y -t 8 -r 500000,500000
    divergence_time: 10700000
  - name: mPanPan1
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/asm_primates/mPanPan1.matpat.v1.fa
    bed: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/regions_primates/mPanPan1.matpat.v1.centromeric_regions.bed
    mm2_opts: -x asm20 -K 8G --eqx -Y -t 8 -r 500000,500000
    divergence_time: 6200000
  - name: mPanTro3
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/asm_primates/mPanTro3.hap1hap2.v1.fa
    bed: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/regions_primates/mPanTro3.hap1hap2.v1.centromeric_regions.bed
    mm2_opts: -x asm20 -K 8G --eqx -Y -t 8 -r 500000,500000
    divergence_time: 6200000
  - name: mPonAbe1
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/asm_primates/mPonAbe1.hap1hap2.v3.fa
    bed: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/regions_primates/mPonAbe1.hap1hap2.v3.centromeric_regions.bed
    mm2_opts: -x asm20 -K 8G --eqx -Y -t 8 -r 500000,500000
    divergence_time: 19100000
  - name: mPonPyg2
    path: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/asm_primates/mPonPyg2.hap1hap2.v3.fa
    bed: /project/logsdon_shared/projects/HGSVC3/Snakemake-MutationRate/data/regions_primates/mPonPyg2.hap1hap2.v3.centromeric_regions.bed
    mm2_opts: -x asm20 -K 8G --eqx -Y -t 8 -r 500000,500000
    divergence_time: 19100000
